"""Add like Model

Revision ID: 5bbbde44aa5c
Revises: e3f25e0cb203
Create Date: 2024-05-08 23:19:49.910195

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5bbbde44aa5c'
down_revision = 'e3f25e0cb203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'like',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date_posted', sa.DateTime(), nullable=False, default=sa.func.now()),
        sa.ForeignKeyConstraint(
            ['post_id'],
            ['post.id'],
            name='fk_like_post',
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['user_id'],
            ['user.id'],
            name='fk_like_user',
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=50), nullable=True, default='default.jpg'))
        batch_op.create_foreign_key('fk_comment_post', 'post', ['post_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('fk_comment_user', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_user', type_='foreignkey')
        batch_op.drop_constraint('fk_comment_post', type_='foreignkey')
        batch_op.drop_column('image_file')
    op.drop_table('like')
    # ### end Alembic commands ###

